const sample = {
  total: 21,
  skip: 0,
  limit: 20,
  data: [
    {
      _id: '649b0c54d3564862b1f6fa64',
      title: '20 book',
      description:
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
      discount: 25,
      price: 2500,
      image: [
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTB58BsvuPTLrunlFUjAEklp4XXgcKIpFGppQ&usqp=CAU',
        'https://cdn.shopify.com/s/files/1/0565/7080/6458/collections/marble-geometry-wallpaper-mural.jpg?v=1660198030',
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT35tQrrRZGZ69bcSSrgP2mLrOc7Hclg2X359GaoSdupKdcYw5lzBp7VPNtjZfS_Oxnhsc&usqp=CAU',
        'https://marketplace.canva.com/EAE-xnqWvJk/1/0/1600w/canva-retro-smoke-and-round-light-desktop-wallpapers-JLofAI27pCg.jpg',
      ],
      createdAt: '2023-06-27T16:20:36.308Z',
      updatedAt: '2023-06-27T16:20:36.308Z',
      __v: 0,
    },
    {
      _id: '649b0c40d3564862b1f6fa62',
      title: '19 book',
      description:
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
      discount: 25,
      price: 2500,
      image: [
        'https://cdn.shopify.com/s/files/1/0565/7080/6458/collections/marble-geometry-wallpaper-mural.jpg?v=1660198030',
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT35tQrrRZGZ69bcSSrgP2mLrOc7Hclg2X359GaoSdupKdcYw5lzBp7VPNtjZfS_Oxnhsc&usqp=CAU',
        'https://marketplace.canva.com/EAE-xnqWvJk/1/0/1600w/canva-retro-smoke-and-round-light-desktop-wallpapers-JLofAI27pCg.jpg',
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTB58BsvuPTLrunlFUjAEklp4XXgcKIpFGppQ&usqp=CAU',
      ],
      createdAt: '2023-06-27T16:20:16.027Z',
      updatedAt: '2023-06-27T16:20:16.027Z',
      __v: 0,
    },
    {
      _id: '649b0c29d3564862b1f6fa60',
      title: '19 book',
      description:
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
      discount: 25,
      price: 2500,
      image: [
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT35tQrrRZGZ69bcSSrgP2mLrOc7Hclg2X359GaoSdupKdcYw5lzBp7VPNtjZfS_Oxnhsc&usqp=CAU',
        'https://marketplace.canva.com/EAE-xnqWvJk/1/0/1600w/canva-retro-smoke-and-round-light-desktop-wallpapers-JLofAI27pCg.jpg',
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTB58BsvuPTLrunlFUjAEklp4XXgcKIpFGppQ&usqp=CAU',
        'https://cdn.shopify.com/s/files/1/0565/7080/6458/collections/marble-geometry-wallpaper-mural.jpg?v=1660198030',
      ],
      createdAt: '2023-06-27T16:19:53.247Z',
      updatedAt: '2023-06-27T16:19:53.247Z',
      __v: 0,
    },
    {
      _id: '649b0c25d3564862b1f6fa5e',
      title: '17 book',
      description:
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
      discount: 25,
      price: 2500,
      image: [
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT35tQrrRZGZ69bcSSrgP2mLrOc7Hclg2X359GaoSdupKdcYw5lzBp7VPNtjZfS_Oxnhsc&usqp=CAU',
        'https://marketplace.canva.com/EAE-xnqWvJk/1/0/1600w/canva-retro-smoke-and-round-light-desktop-wallpapers-JLofAI27pCg.jpg',
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTB58BsvuPTLrunlFUjAEklp4XXgcKIpFGppQ&usqp=CAU',
        'https://cdn.shopify.com/s/files/1/0565/7080/6458/collections/marble-geometry-wallpaper-mural.jpg?v=1660198030',
      ],
      createdAt: '2023-06-27T16:19:49.164Z',
      updatedAt: '2023-06-27T16:19:49.164Z',
      __v: 0,
    },
    {
      _id: '649b0c21d3564862b1f6fa5c',
      title: '16 book',
      description:
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
      discount: 25,
      price: 2500,
      image: [
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT35tQrrRZGZ69bcSSrgP2mLrOc7Hclg2X359GaoSdupKdcYw5lzBp7VPNtjZfS_Oxnhsc&usqp=CAU',
        'https://marketplace.canva.com/EAE-xnqWvJk/1/0/1600w/canva-retro-smoke-and-round-light-desktop-wallpapers-JLofAI27pCg.jpg',
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTB58BsvuPTLrunlFUjAEklp4XXgcKIpFGppQ&usqp=CAU',
        'https://cdn.shopify.com/s/files/1/0565/7080/6458/collections/marble-geometry-wallpaper-mural.jpg?v=1660198030',
      ],
      createdAt: '2023-06-27T16:19:45.129Z',
      updatedAt: '2023-06-27T16:19:45.129Z',
      __v: 0,
    },
    {
      _id: '649b0c1dd3564862b1f6fa5a',
      title: '15 book',
      description:
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
      discount: 25,
      price: 2500,
      image: [
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT35tQrrRZGZ69bcSSrgP2mLrOc7Hclg2X359GaoSdupKdcYw5lzBp7VPNtjZfS_Oxnhsc&usqp=CAU',
        'https://marketplace.canva.com/EAE-xnqWvJk/1/0/1600w/canva-retro-smoke-and-round-light-desktop-wallpapers-JLofAI27pCg.jpg',
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTB58BsvuPTLrunlFUjAEklp4XXgcKIpFGppQ&usqp=CAU',
        'https://cdn.shopify.com/s/files/1/0565/7080/6458/collections/marble-geometry-wallpaper-mural.jpg?v=1660198030',
      ],
      createdAt: '2023-06-27T16:19:41.405Z',
      updatedAt: '2023-06-27T16:19:41.405Z',
      __v: 0,
    },
    {
      _id: '649b0c1ad3564862b1f6fa58',
      title: '14 book',
      description:
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
      discount: 25,
      price: 2500,
      image: [
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT35tQrrRZGZ69bcSSrgP2mLrOc7Hclg2X359GaoSdupKdcYw5lzBp7VPNtjZfS_Oxnhsc&usqp=CAU',
        'https://marketplace.canva.com/EAE-xnqWvJk/1/0/1600w/canva-retro-smoke-and-round-light-desktop-wallpapers-JLofAI27pCg.jpg',
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTB58BsvuPTLrunlFUjAEklp4XXgcKIpFGppQ&usqp=CAU',
        'https://cdn.shopify.com/s/files/1/0565/7080/6458/collections/marble-geometry-wallpaper-mural.jpg?v=1660198030',
      ],
      createdAt: '2023-06-27T16:19:38.083Z',
      updatedAt: '2023-06-27T16:19:38.083Z',
      __v: 0,
    },
    {
      _id: '649b0c15d3564862b1f6fa56',
      title: '13 book',
      description:
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
      discount: 25,
      price: 2500,
      image: [
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT35tQrrRZGZ69bcSSrgP2mLrOc7Hclg2X359GaoSdupKdcYw5lzBp7VPNtjZfS_Oxnhsc&usqp=CAU',
        'https://marketplace.canva.com/EAE-xnqWvJk/1/0/1600w/canva-retro-smoke-and-round-light-desktop-wallpapers-JLofAI27pCg.jpg',
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTB58BsvuPTLrunlFUjAEklp4XXgcKIpFGppQ&usqp=CAU',
        'https://cdn.shopify.com/s/files/1/0565/7080/6458/collections/marble-geometry-wallpaper-mural.jpg?v=1660198030',
      ],
      createdAt: '2023-06-27T16:19:33.846Z',
      updatedAt: '2023-06-27T16:19:33.846Z',
      __v: 0,
    },
    {
      _id: '649b0c12d3564862b1f6fa54',
      title: '12 book',
      description:
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
      discount: 25,
      price: 2500,
      image: [
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT35tQrrRZGZ69bcSSrgP2mLrOc7Hclg2X359GaoSdupKdcYw5lzBp7VPNtjZfS_Oxnhsc&usqp=CAU',
        'https://marketplace.canva.com/EAE-xnqWvJk/1/0/1600w/canva-retro-smoke-and-round-light-desktop-wallpapers-JLofAI27pCg.jpg',
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTB58BsvuPTLrunlFUjAEklp4XXgcKIpFGppQ&usqp=CAU',
        'https://cdn.shopify.com/s/files/1/0565/7080/6458/collections/marble-geometry-wallpaper-mural.jpg?v=1660198030',
      ],
      createdAt: '2023-06-27T16:19:30.456Z',
      updatedAt: '2023-06-27T16:19:30.456Z',
      __v: 0,
    },
    {
      _id: '649b0c0ad3564862b1f6fa52',
      title: 'eleven book',
      description:
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
      discount: 25,
      price: 2500,
      image: [
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT35tQrrRZGZ69bcSSrgP2mLrOc7Hclg2X359GaoSdupKdcYw5lzBp7VPNtjZfS_Oxnhsc&usqp=CAU',
        'https://marketplace.canva.com/EAE-xnqWvJk/1/0/1600w/canva-retro-smoke-and-round-light-desktop-wallpapers-JLofAI27pCg.jpg',
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTB58BsvuPTLrunlFUjAEklp4XXgcKIpFGppQ&usqp=CAU',
        'https://cdn.shopify.com/s/files/1/0565/7080/6458/collections/marble-geometry-wallpaper-mural.jpg?v=1660198030',
      ],
      createdAt: '2023-06-27T16:19:22.450Z',
      updatedAt: '2023-06-27T16:19:22.450Z',
      __v: 0,
    },
    {
      _id: '649b0c05d3564862b1f6fa50',
      title: 'ten book',
      description:
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
      discount: 25,
      price: 2500,
      image: [
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT35tQrrRZGZ69bcSSrgP2mLrOc7Hclg2X359GaoSdupKdcYw5lzBp7VPNtjZfS_Oxnhsc&usqp=CAU',
        'https://marketplace.canva.com/EAE-xnqWvJk/1/0/1600w/canva-retro-smoke-and-round-light-desktop-wallpapers-JLofAI27pCg.jpg',
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTB58BsvuPTLrunlFUjAEklp4XXgcKIpFGppQ&usqp=CAU',
        'https://cdn.shopify.com/s/files/1/0565/7080/6458/collections/marble-geometry-wallpaper-mural.jpg?v=1660198030',
      ],
      createdAt: '2023-06-27T16:19:17.088Z',
      updatedAt: '2023-06-27T16:19:17.088Z',
      __v: 0,
    },
    {
      _id: '649b0bfed3564862b1f6fa4e',
      title: 'nine book',
      description:
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
      discount: 25,
      price: 2500,
      image: [
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT35tQrrRZGZ69bcSSrgP2mLrOc7Hclg2X359GaoSdupKdcYw5lzBp7VPNtjZfS_Oxnhsc&usqp=CAU',
        'https://marketplace.canva.com/EAE-xnqWvJk/1/0/1600w/canva-retro-smoke-and-round-light-desktop-wallpapers-JLofAI27pCg.jpg',
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTB58BsvuPTLrunlFUjAEklp4XXgcKIpFGppQ&usqp=CAU',
        'https://cdn.shopify.com/s/files/1/0565/7080/6458/collections/marble-geometry-wallpaper-mural.jpg?v=1660198030',
      ],
      createdAt: '2023-06-27T16:19:10.740Z',
      updatedAt: '2023-06-27T16:19:10.740Z',
      __v: 0,
    },
    {
      _id: '649b0bfad3564862b1f6fa4c',
      title: 'eight book',
      description:
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
      discount: 25,
      price: 2500,
      image: [
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT35tQrrRZGZ69bcSSrgP2mLrOc7Hclg2X359GaoSdupKdcYw5lzBp7VPNtjZfS_Oxnhsc&usqp=CAU',
        'https://marketplace.canva.com/EAE-xnqWvJk/1/0/1600w/canva-retro-smoke-and-round-light-desktop-wallpapers-JLofAI27pCg.jpg',
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTB58BsvuPTLrunlFUjAEklp4XXgcKIpFGppQ&usqp=CAU',
        'https://cdn.shopify.com/s/files/1/0565/7080/6458/collections/marble-geometry-wallpaper-mural.jpg?v=1660198030',
      ],
      createdAt: '2023-06-27T16:19:06.273Z',
      updatedAt: '2023-06-27T16:19:06.273Z',
      __v: 0,
    },
    {
      _id: '649b0bf4d3564862b1f6fa4a',
      title: 'seven book',
      description:
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
      discount: 25,
      price: 2500,
      image: [
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT35tQrrRZGZ69bcSSrgP2mLrOc7Hclg2X359GaoSdupKdcYw5lzBp7VPNtjZfS_Oxnhsc&usqp=CAU',
        'https://marketplace.canva.com/EAE-xnqWvJk/1/0/1600w/canva-retro-smoke-and-round-light-desktop-wallpapers-JLofAI27pCg.jpg',
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTB58BsvuPTLrunlFUjAEklp4XXgcKIpFGppQ&usqp=CAU',
        'https://cdn.shopify.com/s/files/1/0565/7080/6458/collections/marble-geometry-wallpaper-mural.jpg?v=1660198030',
      ],
      createdAt: '2023-06-27T16:19:00.882Z',
      updatedAt: '2023-06-27T16:19:00.882Z',
      __v: 0,
    },
    {
      _id: '649b0bf1d3564862b1f6fa48',
      title: 'six book',
      description:
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
      discount: 25,
      price: 2500,
      image: [
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT35tQrrRZGZ69bcSSrgP2mLrOc7Hclg2X359GaoSdupKdcYw5lzBp7VPNtjZfS_Oxnhsc&usqp=CAU',
        'https://marketplace.canva.com/EAE-xnqWvJk/1/0/1600w/canva-retro-smoke-and-round-light-desktop-wallpapers-JLofAI27pCg.jpg',
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTB58BsvuPTLrunlFUjAEklp4XXgcKIpFGppQ&usqp=CAU',
        'https://cdn.shopify.com/s/files/1/0565/7080/6458/collections/marble-geometry-wallpaper-mural.jpg?v=1660198030',
      ],
      createdAt: '2023-06-27T16:18:57.279Z',
      updatedAt: '2023-06-27T16:18:57.279Z',
      __v: 0,
    },
    {
      _id: '649b0bebd3564862b1f6fa46',
      title: 'five book',
      description:
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
      discount: 25,
      price: 2500,
      image: [
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT35tQrrRZGZ69bcSSrgP2mLrOc7Hclg2X359GaoSdupKdcYw5lzBp7VPNtjZfS_Oxnhsc&usqp=CAU',
        'https://marketplace.canva.com/EAE-xnqWvJk/1/0/1600w/canva-retro-smoke-and-round-light-desktop-wallpapers-JLofAI27pCg.jpg',
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTB58BsvuPTLrunlFUjAEklp4XXgcKIpFGppQ&usqp=CAU',
        'https://cdn.shopify.com/s/files/1/0565/7080/6458/collections/marble-geometry-wallpaper-mural.jpg?v=1660198030',
      ],
      createdAt: '2023-06-27T16:18:51.180Z',
      updatedAt: '2023-06-27T16:18:51.180Z',
      __v: 0,
    },
    {
      _id: '649b0be5d3564862b1f6fa44',
      title: 'fourth book',
      description:
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
      discount: 25,
      price: 2500,
      image: [
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT35tQrrRZGZ69bcSSrgP2mLrOc7Hclg2X359GaoSdupKdcYw5lzBp7VPNtjZfS_Oxnhsc&usqp=CAU',
        'https://marketplace.canva.com/EAE-xnqWvJk/1/0/1600w/canva-retro-smoke-and-round-light-desktop-wallpapers-JLofAI27pCg.jpg',
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTB58BsvuPTLrunlFUjAEklp4XXgcKIpFGppQ&usqp=CAU',
        'https://cdn.shopify.com/s/files/1/0565/7080/6458/collections/marble-geometry-wallpaper-mural.jpg?v=1660198030',
      ],
      createdAt: '2023-06-27T16:18:45.988Z',
      updatedAt: '2023-06-27T16:18:45.988Z',
      __v: 0,
    },
    {
      _id: '649b0be1d3564862b1f6fa42',
      title: 'third book',
      description:
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
      discount: 25,
      price: 2500,
      image: [
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT35tQrrRZGZ69bcSSrgP2mLrOc7Hclg2X359GaoSdupKdcYw5lzBp7VPNtjZfS_Oxnhsc&usqp=CAU',
        'https://marketplace.canva.com/EAE-xnqWvJk/1/0/1600w/canva-retro-smoke-and-round-light-desktop-wallpapers-JLofAI27pCg.jpg',
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTB58BsvuPTLrunlFUjAEklp4XXgcKIpFGppQ&usqp=CAU',
        'https://cdn.shopify.com/s/files/1/0565/7080/6458/collections/marble-geometry-wallpaper-mural.jpg?v=1660198030',
      ],
      createdAt: '2023-06-27T16:18:41.189Z',
      updatedAt: '2023-06-27T16:18:41.189Z',
      __v: 0,
    },
    {
      _id: '649b0bbfd3564862b1f6fa40',
      title: 'second book',
      description:
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
      discount: 25,
      price: 2500,
      image: [
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT35tQrrRZGZ69bcSSrgP2mLrOc7Hclg2X359GaoSdupKdcYw5lzBp7VPNtjZfS_Oxnhsc&usqp=CAU',
        'https://marketplace.canva.com/EAE-xnqWvJk/1/0/1600w/canva-retro-smoke-and-round-light-desktop-wallpapers-JLofAI27pCg.jpg',
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTB58BsvuPTLrunlFUjAEklp4XXgcKIpFGppQ&usqp=CAU',
        'https://cdn.shopify.com/s/files/1/0565/7080/6458/collections/marble-geometry-wallpaper-mural.jpg?v=1660198030',
      ],
      createdAt: '2023-06-27T16:18:07.074Z',
      updatedAt: '2023-06-27T16:18:07.074Z',
      __v: 0,
    },
    {
      _id: '649b0ba5d3564862b1f6fa3e',
      title: 'second book',
      description:
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
      discount: 10,
      price: 1000,
      image: [
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT35tQrrRZGZ69bcSSrgP2mLrOc7Hclg2X359GaoSdupKdcYw5lzBp7VPNtjZfS_Oxnhsc&usqp=CAU',
        'https://marketplace.canva.com/EAE-xnqWvJk/1/0/1600w/canva-retro-smoke-and-round-light-desktop-wallpapers-JLofAI27pCg.jpg',
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTB58BsvuPTLrunlFUjAEklp4XXgcKIpFGppQ&usqp=CAU',
        'https://cdn.shopify.com/s/files/1/0565/7080/6458/collections/marble-geometry-wallpaper-mural.jpg?v=1660198030',
      ],
      createdAt: '2023-06-27T16:17:41.509Z',
      updatedAt: '2023-06-27T16:17:41.509Z',
      __v: 0,
    },
  ],
};

export {sample};
